export default {
  APP_INITIALIZED_SUCCESS: 'APP_INITIALIZED_SUCCESS',
  DROPPED_SOUND_SUCCESS: 'DROPPED_SOUND_SUCCESS',
  FETCH_SOUND_START: 'FETCH_SOUND_START',
  FETCH_SOUND_SUCCESS: 'FETCH_SOUND_SUCCESS',
  FETCH_SOUND_FAILURE: 'FETCH_SOUND_FAILURE',
  MOVE_SOUND_SUCCESS: 'MOVE_SOUND_SUCCESS',
  PLAY_SOUNDS_SUCCESS: 'PLAY_SOUNDS_SUCCESS',
  PLAY_SOUND_SUCCESS: 'PLAY_SOUND_SUCCESS',
  REMOVE_SOUND_SUCCESS: 'REMOVE_SOUND_SUCCESS',
};
